### ISSUE TITLE
TextureView doesn't support displaying a background drawable

### ISSUE THREAD

**Issue by Servus7** [jcampbell05/NiceSupportMapFragment#5]
`java.lang.UnsupportedOperationException: TextureView doesn't support displaying a background drawable
	at android.view.TextureView.setBackgroundDrawable(TextureView.java:302)
	at android.view.View.setBackground(View.java:18120)
	at android.view.View.setBackgroundColor(View.java:18082)
	at com.stampay.consumer.android.views.NiceSupportMapFragment.onCreateView(SourceFile:99)
`

Huawei Nexus 6P, Android 7.0

**Comment by jcampbell05** [comment]
Thanks for your PR @Servus7 , was a really big help. I hope you're having a great experience with this library.

**Comment by jcampbell05** [comment]
@Servus7  Do you mind building a a .jar file from this tweak and pushing it the repository ?

**Comment by Servus7** [comment]
Hello @jcampbell05. I could upgrade the project to gradle to make .jar generating more easy. And i would like to add some new features for loading maps in a thread.

So. Yes, i like to become a contributor to this library.

**Comment by jcampbell05** [comment]
@Servus7 that would be great!

I've just sent you a invitation so you can collaborate on this.

**Comment by yasirtahir** [comment]
@Servus7, from where I can get the latest .jar file containing this fix?

**Comment by Servus7** [comment]
@yasirtahir Please take a look at #10. You can find the new .jar as a changed file.

**Comment by Servus7** [comment]
#10

**Comment by yasirtahir** [comment]
@Servus7, Thanks!
